# Nginx RTMP configuration for OBS -> RTMP -> HLS streaming

worker_processes  1;
events {
    worker_connections  1024;
}

http {
    sendfile on;
    tcp_nopush on;
    # aio on;
    # directio 512;
    default_type application/octet-stream;
    server {
        listen 8080;
        server_name localhost;

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root "c:/Users/anaka/OneDrive/Documents/mobile app/church app/nginx/temp";
            add_header Cache-Control "no-cache, no-store, must-revalidate, pre-check=0, post-check=0";
            add_header Pragma "no-cache";
            add_header Expires "0";
            add_header Access-Control-Allow-Origin *;
        }

        location / { 
            return 404;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            hls on;
            hls_path "c:/Users/anaka/OneDrive/Documents/mobile app/church app/nginx/temp/hls";
            hls_fragment 3;
            hls_playlist_length 60;
            hls_cleanup on;

            on_publish http://127.0.0.1:8000/api/livestream/notify/?action=start;
            on_publish_done http://127.0.0.1:8000/api/livestream/notify/?action=stop;
        }
    }
}
