# Generated by Django 6.0.5 on 2026-06-03 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_videogroup_customuser_is_pastor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid username. This value may contain only letters, numbers, spaces and @/./+/-/_ characters.', regex='^[\\w.@+\\-\\s]+$')], verbose_name='username'),
        ),
    ]
