# Generated by Django 6.0.5 on 2026-06-03 11:57

from django.db import migrations, models
from django.utils.text import slugify


def populate_stream_keys(apps, schema_editor):
    Pastor = apps.get_model('missions', 'Pastor')
    for pastor in Pastor.objects.all():
        if not pastor.stream_key:
            base_key = slugify(pastor.name) or 'pastor'
            candidate = base_key
            index = 1
            while Pastor.objects.filter(stream_key=candidate).exists():
                index += 1
                candidate = f"{base_key}-{index}"
            pastor.stream_key = candidate
            pastor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastor',
            name='stream_key',
            field=models.CharField(blank=True, null=True, help_text='RTMP/HLS stream key for OBS and viewer playback', max_length=100, unique=True),
        ),
        migrations.RunPython(populate_stream_keys, migrations.RunPython.noop),
    ]
