# Generated by Django 6.0.5 on 2026-06-23 18:13 (manually edited for unique UUID population)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_approval_tokens(apps, schema_editor):
    """Assign a unique UUID token to every existing user."""
    CustomUser = apps.get_model('missions', 'CustomUser')
    for user in CustomUser.objects.all():
        user.approval_token = uuid.uuid4()
        user.save(update_fields=['approval_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_pastor_stream_key'),
    ]

    operations = [
        # Step 1: Add approval_status (default 'approved' so existing users stay active)
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(
                choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='approved',
                help_text='Account approval status',
                max_length=20,
            ),
        ),
        # Step 2: Add approval_token WITHOUT unique constraint first
        migrations.AddField(
            model_name='customuser',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        # Step 3: Populate each row with a real unique UUID
        migrations.RunPython(populate_approval_tokens, migrations.RunPython.noop),
        # Step 4: Now add the unique constraint
        migrations.AlterField(
            model_name='customuser',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # Step 5: Remaining fields
        migrations.AddField(
            model_name='customuser',
            name='approval_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason provided by pastor on rejection'),
        ),
        migrations.AddField(
            model_name='pastor',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="Pastor's email address for approval notifications", max_length=254),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('via_email_link', models.BooleanField(default=False, help_text='True if actioned via email token link')),
                ('actioned_by', models.ForeignKey(
                    blank=True, null=True,
                    help_text='Which user/pastor performed the action (null = email token link)',
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approval_actions_taken',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('pastor', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approval_logs',
                    to='missions.pastor',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='approval_logs',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
