# Generated by Django 6.0.5 on 2026-06-27 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_approval_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('special_prayer', 'Special Prayer'), ('meeting', 'Meeting'), ('service', 'Service'), ('other', 'Other')], default='meeting', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=180)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_events', to=settings.AUTH_USER_MODEL)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_events', to='missions.pastor')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
